include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false

    # if localized one needs to take this in for generated code
    #always_declare_return_types: false
